/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas_6;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class barang extends javax.swing.JFrame {

    /**
     * Creates new form barang
     */
    public barang() {
        initComponents();
        initComponents();
        DefaultTableModel dataModel = (DefaultTableModel) tabelelektronik.getModel();
        int rowCount = dataModel.getRowCount();
        while (rowCount > 0) {
            dataModel.removeRow(rowCount - 1);
            rowCount = dataModel.getRowCount(); // Update rowCount after removal
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtwarna = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbjenis = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        txtjumblah = new javax.swing.JTextField();
        btnproses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelelektronik = new javax.swing.JTable();
        cmbnama = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Keuangan Elektronik");

        jLabel2.setText("Jenis Elekronik");

        jLabel3.setText("Warna");

        jLabel4.setText("Metode Pembayaran");

        jLabel5.setText("Kode Elektronik");

        jLabel6.setText("Harga");

        jLabel7.setText("Jumblah");

        btnproses.setText("input");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });

        tabelelektronik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Jenis elektronik", "warna", "metode pembayaran", "Kode elektronik", "harga", "jumblah", "total"
            }
        ));
        jScrollPane1.setViewportView(tabelelektronik);

        cmbnama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "printer", "music box", "laptop", " " }));
        cmbnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(btnproses))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtwarna)
                                    .addComponent(cmbjenis, 0, 90, Short.MAX_VALUE)
                                    .addComponent(cmbnama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtjumblah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 339, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtwarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtjumblah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnproses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        // TODO add your handling code here:
        String elektronik="";
        if (cmbnama.getSelectedIndex()==0){
            laptop l = new laptop();
            l.datametode((String) cmbjenis.getSelectedItem());
            l.datawarna(txtwarna.getText());
            l.datajenis((String)cmbnama.getSelectedItem());
            l.kdhp(txtkode.getText());
            l.datajumblah(Integer.parseInt(txtjumblah.getText()));
            l.dataharga(Integer.parseInt(txtharga.getText()));
            
            
            laptop harga= new laptop();
            harga.dataharga(Integer.parseInt(txtharga.getText()));
            harga.datajumblah(Integer.parseInt(txtjumblah.getText()));
            JOptionPane.showMessageDialog(this,l.input(l.jenis) );
            tabelelektronik.setAutoCreateColumnsFromModel(true);
        DefaultTableModel dataModel = (DefaultTableModel) tabelelektronik.getModel();
        List list = new ArrayList<>();
        list.add(l.jenis);
        list.add(l.warna);
        list.add(l.metode);
        list.add(l.kode_barang);
        list.add(l.jumblah);
        list.add(l.harga);
        list.add(l.totalharga());
        dataModel.addRow(list.toArray());
        } else if (cmbnama.getSelectedIndex()==1){
            musicbox m = new musicbox();
            m.datametode((String)cmbjenis.getSelectedItem());
            m.datawarna(txtwarna.getText());
            m.datajenis((String)cmbnama.getSelectedItem());
            m.kdhp(txtkode.getText());
            m.datajumblah(Integer.parseInt(txtjumblah.getText()));
            m.dataharga(Integer.parseInt(txtharga.getText()));
            
            
            musicbox harga= new musicbox();
            harga.dataharga(Integer.parseInt(txtharga.getText()));
            harga.datajumblah(Integer.parseInt(txtjumblah.getText()));
            JOptionPane.showMessageDialog(this,m.input(m.jenis) );
            tabelelektronik.setAutoCreateColumnsFromModel(true);
        DefaultTableModel dataModel = (DefaultTableModel) tabelelektronik.getModel();
        List list = new ArrayList<>();
        list.add(m.jenis);
        list.add(m.warna);
        list.add(m.metode);
        list.add(m.kode_barang);
        list.add(m.jumblah);
        list.add(m.harga);
        list.add(m.totalharga());
        dataModel.addRow(list.toArray());
        } else if (cmbnama.getSelectedIndex()==2){
           printer p = new printer();
            p.datametode((String)cmbjenis.getSelectedItem());
            p.datawarna(txtwarna.getText());
            p.datajenis((String)cmbnama.getSelectedItem());
            p.kdhp(txtkode.getText());
            p.datajumblah(Integer.parseInt(txtjumblah.getText()));
            p.dataharga(Integer.parseInt(txtharga.getText()));
            
            
            printer harga= new printer();
            harga.dataharga(Integer.parseInt(txtharga.getText()));
            harga.datajumblah(Integer.parseInt(txtjumblah.getText()));
            JOptionPane.showMessageDialog(this,p.input(p.jenis) );
            tabelelektronik.setAutoCreateColumnsFromModel(true);
        DefaultTableModel dataModel = (DefaultTableModel) tabelelektronik.getModel();
        List list = new ArrayList<>();
        list.add(p.jenis);
        list.add(p.warna);
        list.add(p.metode);
        list.add(p.kode_barang);
        list.add(p.jumblah);
        list.add(p.harga);
        list.add(p.totalharga());
        dataModel.addRow(list.toArray());
}
    }//GEN-LAST:event_btnprosesActionPerformed

    private void cmbnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnamaActionPerformed
         if(cmbnama.getSelectedIndex()==0){
           laptop l = new laptop();
           txtkode.setText(l.kode_barang());
            cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cardles","cash" }));
        } else if (cmbnama.getSelectedIndex()==1){
               musicbox m = new musicbox();
           txtkode.setText(m.kode_barang());
            cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cardles","cash" }));
        } else if (cmbnama.getSelectedIndex()==2){
          printer p = new printer();
           txtkode.setText(p.kode_barang());
            cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cardles","cash" }));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbnamaActionPerformed

    /**
     * @param args the command line arguments
     */
       public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnproses;
    private javax.swing.JComboBox<String> cmbjenis;
    private javax.swing.JComboBox<String> cmbnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelelektronik;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjumblah;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtwarna;
    // End of variables declaration//GEN-END:variables
}
